root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -buildvcs=false -o /app/tmp/main /app/cmd/app"
  bin = "/app/tmp/main"
  full_bin = "/app/tmp/main"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp"]
  delay = 1000

[log]
  time = true
